"""masterplan §12.5: "confidence is computed, never generated by a model" —
except `ResearchBrief.field_confidence`, a deliberate, narrow exception for
routing the disambiguation decision. This asserts the exception stays
narrow: brief confidences can never reach `api.evidence.confidence`
(evidence/finding confidence, which *is* computed), structurally as well as
by convention. Mirrors `test_evidence_no_llm.py`'s AST-import-boundary
style for the same kind of guarantee.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest
from pydantic import ValidationError

import api.planner
from api.evidence.confidence import ConfidenceInputs
from api.models.brief import ResearchBrief


def _imported_modules(path: Path) -> set[str]:
    tree = ast.parse(path.read_text())
    names = {
        alias.name
        for node in ast.walk(tree)
        if isinstance(node, ast.Import)
        for alias in node.names
    }
    names |= {
        node.module
        for node in ast.walk(tree)
        if isinstance(node, ast.ImportFrom) and node.module is not None
    }
    return names


def test_no_module_in_api_planner_imports_api_evidence() -> None:
    package_dir = Path(api.planner.__file__).parent
    for path in sorted(package_dir.glob("*.py")):
        imported = _imported_modules(path)
        offending = {m for m in imported if m == "api.evidence" or m.startswith("api.evidence.")}
        assert not offending, (
            f"{path.name} imports {offending}, but Phase 09 brief confidence "
            "must never touch evidence confidence"
        )


def test_research_brief_has_no_top_level_confidence_field() -> None:
    """Only `field_confidence` (a routing signal) exists — no bare
    `confidence` field that a careless caller could mistake for a finding's
    computed confidence."""
    assert "field_confidence" in ResearchBrief.model_fields
    assert "confidence" not in ResearchBrief.model_fields


def test_field_confidence_shape_is_structurally_incompatible_with_confidence_inputs() -> None:
    """`ConfidenceInputs` (the only constructor of an evidence-confidence
    number, `api.evidence.confidence.confidence`) requires `best_grade`,
    `n_distinct_domains`, `age_days`, `contradicted` — a `dict[str, float]`
    like `field_confidence` cannot satisfy it, so there is no way to pass a
    brief's confidences into the computed-confidence path even by
    accident."""
    field_confidence = {"segment": 0.55, "geography": 0.40}
    with pytest.raises(ValidationError):
        ConfidenceInputs(**field_confidence)  # type: ignore[arg-type]
